//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDR_Contient_Composants_Modules
    {
        public int Comp_Index { get; set; }
        public int Mod_Index { get; set; }
        public Nullable<int> Comp_Nbr { get; set; }
    
        public virtual MDR_Composants MDR_Composants { get; set; }
        public virtual MDR_Modules MDR_Modules { get; set; }
    }
}
