//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MADERA_V1Entities : DbContext
    {
        public MADERA_V1Entities()
            : base("name=MADERA_V1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MDR_Clients> MDR_Clients { get; set; }
        public virtual DbSet<MDR_Commandes> MDR_Commandes { get; set; }
        public virtual DbSet<MDR_Commerciaux> MDR_Commerciaux { get; set; }
        public virtual DbSet<MDR_Composants> MDR_Composants { get; set; }
        public virtual DbSet<MDR_Contient_Composants_Modules> MDR_Contient_Composants_Modules { get; set; }
        public virtual DbSet<MDR_Devis> MDR_Devis { get; set; }
        public virtual DbSet<MDR_Etat_Paiement> MDR_Etat_Paiement { get; set; }
        public virtual DbSet<MDR_Fournisseurs> MDR_Fournisseurs { get; set; }
        public virtual DbSet<MDR_Gammes> MDR_Gammes { get; set; }
        public virtual DbSet<MDR_Modeles> MDR_Modeles { get; set; }
        public virtual DbSet<MDR_Modules> MDR_Modules { get; set; }
        public virtual DbSet<MDR_Paiement> MDR_Paiement { get; set; }
        public virtual DbSet<MDR_Sites> MDR_Sites { get; set; }
        public virtual DbSet<MDR_Types_Paiement> MDR_Types_Paiement { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
